### ISSUE TITLE
set result doesn't work right

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-graphql#104]
0 balance BOT address can set result. 
And after set result, the topic won't go to vote.

**Comment by frankobe** [comment]
@henryzbw as discussed, please provide all details like db oracle row etc to facilitate the debug
Based on initial investigation, oracle remains openresultset in db, should be an UI update lagging

**Comment by henryzbw** [comment]
{"_id":"3625a0dc06355a14110ad89e3fd4bc1b1492563a","version":0,"address":"3625a0dc06355a14110ad89e3fd4bc1b1492563a","txid":"5c9ef8ac76b46b8825836c097d34c4bd2f0aa4fdf394d23278375c71ea3183f0","topicAddress":"47e708ee31396c7c62358e50438ce1412477f59b","resultSetterAddress":"17e7888aa7412a735f336d2f6d784caefabb6fa3","resultSetterQAddress":"qKjn4fStBaAtwGiwueJf9qFxgpbAvf1xAy","status":"OPENRESULTSET","token":"QTUM","name":"What is the most popular topping on pizza?","options":["Invalid","Pepperoni","Mushroom","Sausage","Onions","Anchoives"],"optionIdxs":[0,1,2,3,4,5],"amounts":["0","0","0","0","0","0"],"resultIdx":null,"blockNum":78983,"startTime":1517489305,"endTime":1517590799,"resultSetStartTime":1517590800,"resultSetEndTime":1517849999,"consensusThreshold":"2540be400"}

db still shows OPENRESULTSET, so it should be the front end problem, it shouldn't let the 0 bot balance pass the approving.

**Comment by frankobe** [comment]
@henryzbw Thx. Another issue is that this event shouldnt remains the the resultset category even after 0 BOT resultset, can u validate the reason it disappears?
