### ISSUE TITLE
Show Electron errors (dialog) if qtumd has issues starting up

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-graphql#120]

**Comment by dwalintukan** [comment]
@frankobe why close this one?

**Comment by frankobe** [comment]
BE errors shouldnt be thrown as it is for internal usage. Users should be notified when app Start/Reboot/Crash/Exist, so is this for starting qtumd process specifically?

**Comment by dwalintukan** [comment]
@frankobe Ya for qtumd startup errors. Right now, if qtumd throws an error ie. qtum already running, the window will just close and not show any sort of indication of error. This will be a bad experience for end user thinking our app is bugged.

**Comment by dwalintukan** [comment]
#178
