### ISSUE TITLE
need bettingEndBlock and ResultSettingEndBlock

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-graphql#14]
Will need this for post-demo version. 

We need to show on the UI for the CentralizedOracle the range they can set the result. And this also serves as a block number that other users can take over the CentralizedOracle and set the result (after the resultSettingEndBlock).

For DecentralizedOracle, we only need `arbitrationEndBlock`.

**Comment by frankobe** [comment]
@dwalintukan @chrisli30 
For CentralizedOracle
`bettingEndBlock` ->`endBlock`
`resultSettingEndBlock` - > `resultSetEndBlock`

For DecentralizedOracle
`arbitrationEndBlock`  -> `endBlock`
