### ISSUE TITLE
Add escrow withdraw mutation

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-graphql#165]

**Comment by frankobe** [comment]
@dwalintukan why not handle this the same as `withdraw`?

**Comment by dwalintukan** [comment]
@frankobe on a contract level it would've been messy to deal with that included in the winnings. on graph side, going to try to have it hit the same mutation as withdraw winnings.

**Comment by frankobe** [comment]
@dwalintukan My impression is that we calculating it tgt with winning withdraw (seems wrong). The problem with withdrawEscrow is that we need file 2 requests

**Comment by dwalintukan** [comment]
@frankobe We are not calculating it with the winning amount. I was thinking we can execute two txs on graph side if they withdraw from the address that is the creator.

**Comment by dwalintukan** [comment]
#168
