### ISSUE TITLE
Show at least return one address if all addresses have zero balances, otherwise i can't even ask ppl to send me qtum/bot

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-graphql#186]

**Comment by liviavinci** [comment]
<img width="1419" alt="screen shot 2018-04-04 at 9 27 59 am" src="https://user-images.githubusercontent.com/1126827/38283801-b0d03768-37ea-11e8-87b3-a97dfa68db35.png">

**Comment by dwalintukan** [comment]
@liviavinci ill work on this to return the default address if none showing.

**Comment by dwalintukan** [comment]
fixed https://github.com/bodhiproject/bodhi-graphql/pull/187
