### ISSUE TITLE
click on tx id redirect to wrong address

### ISSUE THREAD

**Issue by frankobe** [bodhiproject/bodhi-graphql#205]
click on txid `a793f81732c75f40e9fc8e7d7240a2bd1e3c913b2113c876a4d998df2013985e`

Jump tp `http://127.0.0.1:5555/activities/undefined/tx/a793f81732c75f40e9fc8e7d7240a2bd1e3c913b2113c876a4d998df2013985e`

{"code":"ResourceNotFound","message":"/activities/undefined/tx/a793f81732c75f40e9fc8e7d7240a2bd1e3c913b2113c876a4d998df2013985e; caused by Error: ENOENT, ui/activities/undefined/tx/a793f81732c75f40e9fc8e7d7240a2bd1e3c913b2113c876a4d998df2013985e not found in /Volumes/Bodhi 0.7.0-c0-d0/Bodhi.app/Contents/Resources/app.asar"}

**Comment by dwalintukan** [comment]
#206 fixed
