### ISSUE TITLE
store BN in db

### ISSUE THREAD

**Issue by frankobe** [bodhiproject/bodhi-graphql#21]
BN in solidity is `uint256`, `int` for mongo is 32 bit, `long` is 64 bit

**Comment by chrisli30** [comment]
For balances, if graphql supports BN, return BN; otherwise string.

Note that block numbers are still int.

**Comment by frankobe** [comment]
@chrisli30 @dwalintukan according to BN.js https://github.com/indutny/bn.js/. I cant pass BN in json. Instead, I will pass a hex string from `a.toJSON()` (BN.js doenst support decimal).

For UI, a `BN` object need be init like `var b = new BN('dead', 16);` first. For UI display, this decimal string can be generated like `b.toString(10)`. For any arithmetics operation, u can refer to the part in https://github.com/indutny/bn.js/

**Comment by chrisli30** [comment]
Sounds good to me! Please record what fields have been changed to BN in this thread.
