### ISSUE TITLE
SyncInfo accounts showing zero for a little when restarting app

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-graphql#210]
Not verified yet, but Jack witnessed when starting/restarting the app that the balances would show as zero for all the QTUM/BOT.

possible steps to repro:
1. start app
2. restart app
3. check my wallet page
4. if zero balances showing, might show correct balances on next block

**Comment by dwalintukan** [comment]
Cannot repro this. Possible Windows only bug.

**Comment by frankobe** [comment]
check whether api is up before calling

**Comment by dwalintukan** [comment]
#234
