### ISSUE TITLE
Can't retrieve all topics from graphql with amount update.

### ISSUE THREAD

**Issue by chrisli30** [bodhiproject/bodhi-graphql#22]
The allTopic query which worked fine now returns an error due to large number.
"message": "Int cannot represent non 32-bit signed integer value: 10000000000",

Two issues:
1. Botoshi unit too large for an INT. For short term we convert botoshi to BOT unit before saving to db.

2. In a long term, we need to figure a way to handle large number. This is a low-pri tho, since Int can handle 2^32 and that's large enough for a bet.

**Comment by frankobe** [comment]
@chrisli30 duplicated for #21 so I close it
