### ISSUE TITLE
some Votes missing topicAddress

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-graphql#249]
![image](https://user-images.githubusercontent.com/4350404/39680915-cf8b498e-515a-11e8-9352-fb22834032a7.png)

**Comment by frankobe** [comment]
the root cause is https://github.com/bodhiproject/bodhi-graphql/blob/c194ce48efe9ade6201a9a29904ca2bf3348c92c/src/sync/index.js#L193
