### ISSUE TITLE
Fix route to use graphiql

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-graphql#75]
`http://localhost:5555/graphiql` is routed to the UI instead of graphiql

**Comment by dwalintukan** [comment]
Closing. This is because of the Chrome cache. Works in incognito

**Comment by frankhu-optimizely** [comment]
@dwalintukan I find this one too, though works in incognito mode but wonder why

**Comment by frankobe** [comment]
@dwalintukan I find this one too, though works in incognito mode but wonder why

**Comment by dwalintukan** [comment]
Its the caching with chrome, need to clear the cookies for localhost. But we need to find a solution for this for prod version.

**Comment by frankobe** [comment]
@henryzbw lets host api in a different port like `5556`
